site_name: Formula Student Driverless Simulator
theme: readthedocs
site_description: A virtual world where Autonomous Systems from different Formula Student teams can compete in time-trial challenges
repo_name: FS-Online/Formula-Student-Driverless-Simulator
repo_url: https://github.com/FS-Online/Formula-Student-Driverless-Simulator
edit_uri: 
copyright: GPLv2

nav:
  - "Home": "README.md"
  - "Introduction":
    - "System overview": "system-overview.md"
    - "Integration handbook": "integration-handbook.md"
  - "Usage & Development":
    - "How to simulate": "how-to-simulate.md"
    - "Setup your development environment": "get-ready-to-develop.md" 
    - "How to develop the FSDS project": "how-to-develop.md"
    - "Build your ros workspace": "building-ros.md"
    - "Google cloud remote workstation": "gcp-remote-workstation.md" 
  - "Vehicle & Sensors":
    - "Vehicle model": "vehicle_model.md"
    - "IMU": "imu.md"
    - "GPS": "gps.md"
  - "#tech madness":
    - "ROS Bridge": "ros-bridge.md"
    - "ROS Bridge statistics": "statistics.md"
    - "Joystick": "joystick.md"
    - "Operator": "operator.md"
    - "Spectator": "spectator.md"
    - "Import your 3d car model": "import-car-3d-model.md"
extra_css:
  - css\version-select.css
extra_javascript:
  - js\version-select.js
